export interface Countries {
    code: string
    code3: string
    name: string
    number: string
}


export var countries: Countries [] = [
    {"code": "AF", "code3": "AFG", "name": "Afghanistan", "number": "+93"},
    {"code": "AX", "code3": "ALA", "name": "Åland Islands", "number": "+358"},
    {"code": "AL", "code3": "ALB", "name": "Albania", "number": "+355"},
    {"code": "DZ", "code3": "DZA", "name": "Algeria", "number": "+213"},
    {"code": "AS", "code3": "ASM", "name": "American Samoa", "number": "+1-684"},
    {"code": "AD", "code3": "AND", "name": "Andorra", "number": "+376"},
    {"code": "AO", "code3": "AGO", "name": "Angola", "number": "+244"},
    {"code": "AI", "code3": "AIA", "name": "Anguilla", "number": "+1-264"},
    {"code": "AQ", "code3": "ATA", "name": "Antarctica", "number": ""},
    {"code": "AG", "code3": "ATG", "name": "Antigua and Barbuda", "number": "+1-268"},
    {"code": "AR", "code3": "ARG", "name": "Argentina", "number": "+54"},
    {"code": "AM", "code3": "ARM", "name": "Armenia", "number": "+374"},
    {"code": "AW", "code3": "ABW", "name": "Aruba", "number": "+297"},
    {"code": "AU", "code3": "AUS", "name": "Australia", "number": "+61"},
    {"code": "AT", "code3": "AUT", "name": "Austria", "number": "+43"},
    {"code": "AZ", "code3": "AZE", "name": "Azerbaijan", "number": "+994"},
    {"code": "BS", "code3": "BHS", "name": "Bahamas", "number": "+1-242"},
    {"code": "BH", "code3": "BHR", "name": "Bahrain", "number": "+973"},
    {"code": "BD", "code3": "BGD", "name": "Bangladesh", "number": "+880"},
    {"code": "BB", "code3": "BRB", "name": "Barbados", "number": "+1-246"},
    {"code": "BY", "code3": "BLR", "name": "Belarus", "number": "+375"},
    {"code": "BE", "code3": "BEL", "name": "Belgium", "number": "+32"},
    {"code": "BZ", "code3": "BLZ", "name": "Belize", "number": "+501"},
    {"code": "BJ", "code3": "BEN", "name": "Benin", "number": "+229"},
    {"code": "BM", "code3": "BMU", "name": "Bermuda", "number": "+1-441"},
    {"code": "BT", "code3": "BTN", "name": "Bhutan", "number": "+975"},
    {"code": "BO", "code3": "BOL", "name": "Bolivia", "number": "+591"},
    {"code": "BA", "code3": "BIH", "name": "Bosnia and Herzegovina", "number": "+387"},
    {"code": "BW", "code3": "BWA", "name": "Botswana", "number": "+267"},
    {"code": "BV", "code3": "BVT", "name": "Bouvet Island", "number": ""},
    {"code": "BR", "code3": "BRA", "name": "Brazil", "number": "+55"},
    {"code": "IO", "code3": "IOT", "name": "British Indian Ocean Territory", "number": "+246"},
    {"code": "BN", "code3": "BRN", "name": "Brunei Darussalam", "number": "+673"},
    {"code": "BG", "code3": "BGR", "name": "Bulgaria", "number": "+359"},
    {"code": "BF", "code3": "BFA", "name": "Burkina Faso", "number": "+226"},
    {"code": "BI", "code3": "BDI", "name": "Burundi", "number": "+257"},
    {"code": "KH", "code3": "KHM", "name": "Cambodia", "number": "+855"},
    {"code": "CM", "code3": "CMR", "name": "Cameroon", "number": "+237"},
    {"code": "CA", "code3": "CAN", "name": "Canada", "number": "+1"},
    {"code": "CV", "code3": "CPV", "name": "Cape Verde", "number": "+238"},
    {"code": "KY", "code3": "CYM", "name": "Cayman Islands", "number": "+1-345"},
    {"code": "CF", "code3": "CAF", "name": "Central African Republic", "number": "+236"},
    {"code": "TD", "code3": "TCD", "name": "Chad", "number": "+235"},
    {"code": "CL", "code3": "CHL", "name": "Chile", "number": "+56"},
    {"code": "CN", "code3": "CHN", "name": "China", "number": "+86"},
    {"code": "CX", "code3": "CXR", "name": "Christmas Island", "number": "+61"},
    {"code": "CC", "code3": "CCK", "name": "Cocos (Keeling) Islands", "number": "+61"},
    {"code": "CO", "code3": "COL", "name": "Colombia", "number": "+57"},
    {"code": "KM", "code3": "COM", "name": "Comoros", "number": "+269"},
    {"code": "CG", "code3": "COG", "name": "Congo", "number": "+242"},
    {"code": "CD", "code3": "COD", "name": "Congo, The Democratic Republic of the", "number": "+243"},
    {"code": "CK", "code3": "COK", "name": "Cook Islands", "number": "+682"},
    {"code": "CR", "code3": "CRI", "name": "Costa Rica", "number": "+506"},
    {"code": "CI", "code3": "CIV", "name": "Cote D'Ivoire", "number": "+225"},
    {"code": "HR", "code3": "HRV", "name": "Croatia", "number": "+385"},
    {"code": "CU", "code3": "CUB", "name": "Cuba", "number": "+53"},
    {"code": "CY", "code3": "CYP", "name": "Cyprus", "number": "+357"},
    {"code": "CZ", "code3": "CZE", "name": "Czech Republic", "number": "+420"},
    {"code": "DK", "code3": "DNK", "name": "Denmark", "number": "+45"},
    {"code": "DJ", "code3": "DJI", "name": "Djibouti", "number": "+253"},
    {"code": "DM", "code3": "DMA", "name": "Dominica", "number": "+1-767"},
    {"code": "DO", "code3": "DOM", "name": "Dominican Republic", "number": "+1-809"},
    {"code": "EC", "code3": "ECU", "name": "Ecuador", "number": "+593"},
    {"code": "EG", "code3": "EGY", "name": "Egypt", "number": "+20"},
    {"code": "SV", "code3": "SLV", "name": "El Salvador", "number": "+503"},
    {"code": "GQ", "code3": "GNQ", "name": "Equatorial Guinea", "number": "+240"},
    {"code": "ER", "code3": "ERI", "name": "Eritrea", "number": "+291"},
    {"code": "EE", "code3": "EST", "name": "Estonia", "number": "+372"},
    {"code": "ET", "code3": "ETH", "name": "Ethiopia", "number": "+251"},
    {"code": "FK", "code3": "FLK", "name": "Falkland Islands (Malvinas)", "number": "+500"},
    {"code": "FO", "code3": "FRO", "name": "Faroe Islands", "number": "+298"},
    {"code": "FJ", "code3": "FJI", "name": "Fiji", "number": "+679"},
    {"code": "FI", "code3": "FIN", "name": "Finland", "number": "+358"},
    {"code": "FR", "code3": "FRA", "name": "France", "number": "+33"},
    {"code": "GF", "code3": "GUF", "name": "French Guiana", "number": "+594"},
    {"code": "PF", "code3": "PYF", "name": "French Polynesia", "number": "+689"},
    {"code": "TF", "code3": "ATF", "name": "French Southern Territories", "number": ""},
    {"code": "GA", "code3": "GAB", "name": "Gabon", "number": "+241"},
    {"code": "GM", "code3": "GMB", "name": "Gambia", "number": "+220"},
    {"code": "GE", "code3": "GEO", "name": "Georgia", "number": "+995"},
    {"code": "DE", "code3": "DEU", "name": "Germany", "number": "+49"},
    {"code": "GH", "code3": "GHA", "name": "Ghana", "number": "+233"},
    {"code": "GI", "code3": "GIB", "name": "Gibraltar", "number": "+350"},
    {"code": "GR", "code3": "GRC", "name": "Greece", "number": "+30"},
    {"code": "GL", "code3": "GRL", "name": "Greenland", "number": "+299"},
    {"code": "GD", "code3": "GRD", "name": "Grenada", "number": "+1-473"},
    {"code": "GP", "code3": "GLP", "name": "Guadeloupe", "number": "+590"},
    {"code": "GU", "code3": "GUM", "name": "Guam", "number": "+1-671"},
    {"code": "GT", "code3": "GTM", "name": "Guatemala", "number": "+502"},
    {"code": "GG", "code3": "GGY", "name": "Guernsey", "number": "+44-1481"},
    {"code": "GN", "code3": "GIN", "name": "Guinea", "number": "+224"},
    {"code": "GW", "code3": "GNB", "name": "Guinea-Bissau", "number": "+245"},
    {"code": "GY", "code3": "GUY", "name": "Guyana", "number": "+592"},
    {"code": "HT", "code3": "HTI", "name": "Haiti", "number": "+509"},
    {"code": "HM", "code3": "HMD", "name": "Heard Island and Mcdonald Islands", "number": ""},
    {"code": "VA", "code3": "VAT", "name": "Holy See (Vatican City State)", "number": "+379"},
    {"code": "HN", "code3": "HND", "name": "Honduras", "number": "+504"},
    {"code": "HK", "code3": "HKG", "name": "Hong Kong", "number": "+852"},
    {"code": "HU", "code3": "HUN", "name": "Hungary", "number": "+36"},
    {"code": "IS", "code3": "ISL", "name": "Iceland", "number": "+354"},
    {"code": "IN", "code3": "IND", "name": "India", "number": "+91"},
    {"code": "ID", "code3": "IDN", "name": "Indonesia", "number": "+62"},
    {"code": "IR", "code3": "IRN", "name": "Iran, Islamic Republic Of", "number": "+98"},
    {"code": "IQ", "code3": "IRQ", "name": "Iraq", "number": "+964"},
    {"code": "IE", "code3": "IRL", "name": "Ireland", "number": "+353"},
    {"code": "IM", "code3": "IMN", "name": "Isle of Man", "number": "+44-1624"},
    {"code": "IL", "code3": "ISR", "name": "Israel", "number": "+972"},
    {"code": "IT", "code3": "ITA", "name": "Italy", "number": "+39"},
    {"code": "JM", "code3": "JAM", "name": "Jamaica", "number": "+1-876"},
    {"code": "JP", "code3": "JPN", "name": "Japan", "number": "+81"},
    {"code": "JE", "code3": "JEY", "name": "Jersey", "number": "+44-1534"},
    {"code": "JO", "code3": "JOR", "name": "Jordan", "number": "+962"},
    {"code": "KZ", "code3": "KAZ", "name": "Kazakhstan", "number": "+7"},
    {"code": "KE", "code3": "KEN", "name": "Kenya", "number": "+254"},
    {"code": "KI", "code3": "KIR", "name": "Kiribati", "number": "+686"},
    {"code": "KP", "code3": "PRK", "name": "Korea, Democratic People's Republic of", "number": "+850"},
    {"code": "KR", "code3": "KOR", "name": "Korea, Republic of", "number": "+82"},
    {"code": "KW", "code3": "KWT", "name": "Kuwait", "number": "+965"},
    {"code": "KG", "code3": "KGZ", "name": "Kyrgyzstan", "number": "+996"},
    {"code": "LA", "code3": "LAO", "name": "Lao People's Democratic Republic", "number": "+856"},
    {"code": "LV", "code3": "LVA", "name": "Latvia", "number": "+371"},
    {"code": "LB", "code3": "LBN", "name": "Lebanon", "number": "+961"},
    {"code": "LS", "code3": "LSO", "name": "Lesotho", "number": "+266"},
    {"code": "LR", "code3": "LBR", "name": "Liberia", "number": "+231"},
    {"code": "LY", "code3": "LBY", "name": "Libyan Arab Jamahiriya", "number": "+218"},
    {"code": "LI", "code3": "LIE", "name": "Liechtenstein", "number": "+423"},
    {"code": "LT", "code3": "LTU", "name": "Lithuania", "number": "+370"},
    {"code": "LU", "code3": "LUX", "name": "Luxembourg", "number": "+352"},
    {"code": "MO", "code3": "MAC", "name": "Macao", "number": "+853"},
    {"code": "MK", "code3": "MKD", "name": "Macedonia, The Former Yugoslav Republic of", "number": "+389"},
    {"code": "MG", "code3": "MDG", "name": "Madagascar", "number": "+261"},
    {"code": "MW", "code3": "MWI", "name": "Malawi", "number": "+265"},
    {"code": "MY", "code3": "MYS", "name": "Malaysia", "number": "+60"},
    {"code": "MV", "code3": "MDV", "name": "Maldives", "number": "+960"},
    {"code": "ML", "code3": "MLI", "name": "Mali", "number": "+223"},
    {"code": "MT", "code3": "MLT", "name": "Malta", "number": "+356"},
    {"code": "MH", "code3": "MHL", "name": "Marshall Islands", "number": "+692"},
    {"code": "MQ", "code3": "MTQ", "name": "Martinique", "number": "+596"},
    {"code": "MR", "code3": "MRT", "name": "Mauritania", "number": "+222"},
    {"code": "MU", "code3": "MUS", "name": "Mauritius", "number": "+230"},
    {"code": "YT", "code3": "MYT", "name": "Mayotte", "number": "+262"},
    {"code": "MX", "code3": "MEX", "name": "Mexico", "number": "+52"},
    {"code": "FM", "code3": "FSM", "name": "Micronesia, Federated States of", "number": "+691"},
    {"code": "MD", "code3": "MDA", "name": "Moldova, Republic of", "number": "+373"},
    {"code": "MC", "code3": "MCO", "name": "Monaco", "number": "+377"},
    {"code": "MN", "code3": "MNG", "name": "Mongolia", "number": "+976"},
    {"code": "ME", "code3": "MNE", "name": "Montenegro", "number": "+382"},
    {"code": "MS", "code3": "MSR", "name": "Montserrat", "number": "+1-664"},
    {"code": "MA", "code3": "MAR", "name": "Morocco", "number": "+212"},
    {"code": "MZ", "code3": "MOZ", "name": "Mozambique", "number": "+258"},
    {"code": "MM", "code3": "MMR", "name": "Myanmar", "number": "+95"},
    {"code": "NA", "code3": "NAM", "name": "Namibia", "number": "+264"},
    {"code": "NR", "code3": "NRU", "name": "Nauru", "number": "+674"},
    {"code": "NP", "code3": "NPL", "name": "Nepal", "number": "+977"},
    {"code": "NL", "code3": "NLD", "name": "Netherlands", "number": "+31"},
    {"code": "AN", "code3": "ANT", "name": "Netherlands Antilles", "number": "+599"},
    {"code": "NC", "code3": "NCL", "name": "New Caledonia", "number": "+687"},
    {"code": "NZ", "code3": "NZL", "name": "New Zealand", "number": "+64"},
    {"code": "NI", "code3": "NIC", "name": "Nicaragua", "number": "+505"},
    {"code": "NE", "code3": "NER", "name": "Niger", "number": "+227"},
    {"code": "NG", "code3": "NGA", "name": "Nigeria", "number": "+234"},
    {"code": "NU", "code3": "NIU", "name": "Niue", "number": "+683"},
    {"code": "NF", "code3": "NFK", "name": "Norfolk Island", "number": "+672"},
    {"code": "MP", "code3": "MNP", "name": "Northern Mariana Islands", "number": "+1-670"},
    {"code": "NO", "code3": "NOR", "name": "Norway", "number": "+47"},
    {"code": "OM", "code3": "OMN", "name": "Oman", "number": "+968"},
    {"code": "PK", "code3": "PAK", "name": "Pakistan", "number": "+92"},
    {"code": "PW", "code3": "PLW", "name": "Palau", "number": "+680"},
    {"code": "PS", "code3": "PSE", "name": "Palestinian Territory, Occupied", "number": "+970"},
    {"code": "PA", "code3": "PAN", "name": "Panama", "number": "+507"},
    {"code": "PG", "code3": "PNG", "name": "Papua New Guinea", "number": "+675"},
    {"code": "PY", "code3": "PRY", "name": "Paraguay", "number": "+595"},
    {"code": "PE", "code3": "PER", "name": "Peru", "number": "+51"},
    {"code": "PH", "code3": "PHL", "name": "Philippines", "number": "+63"},
    {"code": "PN", "code3": "PCN", "name": "Pitcairn", "number": "+870"},
    {"code": "PL", "code3": "POL", "name": "Poland", "number": "+48"},
    {"code": "PT", "code3": "PRT", "name": "Portugal", "number": "+351"},
    {"code": "PR", "code3": "PRI", "name": "Puerto Rico", "number": "+1-787"},
    {"code": "QA", "code3": "QAT", "name": "Qatar", "number": "+974"},
    {"code": "RE", "code3": "REU", "name": "Reunion", "number": "+262"},
    {"code": "RO", "code3": "ROU", "name": "Romania", "number": "+40"},
    {"code": "RU", "code3": "RUS", "name": "Russian Federation", "number": "+7"},
    {"code": "RW", "code3": "RWA", "name": "Rwanda", "number": "+250"},
    {"code": "SH", "code3": "SHN", "name": "Saint Helena", "number": "+290"},
    {"code": "KN", "code3": "KNA", "name": "Saint Kitts and Nevis", "number": "+1-869"},
    {"code": "LC", "code3": "LCA", "name": "Saint Lucia", "number": "+1-758"},
    {"code": "PM", "code3": "SPM", "name": "Saint Pierre and Miquelon", "number": "+508"},
    {"code": "VC", "code3": "VCT", "name": "Saint Vincent and the Grenadines", "number": "+1-784"},
    {"code": "WS", "code3": "WSM", "name": "Samoa", "number": "+685"},
    {"code": "SM", "code3": "SMR", "name": "San Marino", "number": "+378"},
    {"code": "ST", "code3": "STP", "name": "Sao Tome and Principe", "number": "+239"},
    {"code": "SA", "code3": "SAU", "name": "Saudi Arabia", "number": "+966"},
    {"code": "SN", "code3": "SEN", "name": "Senegal", "number": "+221"},
    {"code": "RS", "code3": "SRB", "name": "Serbia", "number": "+381"},
    {"code": "SC", "code3": "SYC", "name": "Seychelles", "number": "+248"},
    {"code": "SL", "code3": "SLE", "name": "Sierra Leone", "number": "+232"},
    {"code": "SG", "code3": "SGP", "name": "Singapore", "number": "+65"},
    {"code": "SK", "code3": "SVK", "name": "Slovakia", "number": "+421"},
    {"code": "SI", "code3": "SVN", "name": "Slovenia", "number": "+386"},
    {"code": "SB", "code3": "SLB", "name": "Solomon Islands", "number": "+677"},
    {"code": "SO", "code3": "SOM", "name": "Somalia", "number": "+252"},
    {"code": "ZA", "code3": "ZAF", "name": "South Africa", "number": "+27"},
    {"code": "GS", "code3": "SGS", "name": "South Georgia and the South Sandwich Islands", "number": ""},
    {"code": "ES", "code3": "ESP", "name": "Spain", "number": "+34"},
    {"code": "LK", "code3": "LKA", "name": "Sri Lanka", "number": "+94"},
    {"code": "SD", "code3": "SDN", "name": "Sudan", "number": "+249"},
    {"code": "SR", "code3": "SUR", "name": "Suriname", "number": "+597"},
    {"code": "SJ", "code3": "SJM", "name": "Svalbard and Jan Mayen", "number": "+47"},
    {"code": "SZ", "code3": "SWZ", "name": "Swaziland", "number": "+268"},
    {"code": "SE", "code3": "SWE", "name": "Sweden", "number": "+46"},
    {"code": "CH", "code3": "CHE", "name": "Switzerland", "number": "+41"},
    {"code": "SY", "code3": "SYR", "name": "Syrian Arab Republic", "number": "+963"},
    {"code": "TW", "code3": "TWN", "name": "Taiwan, Province of China", "number": "+886"},
    {"code": "TJ", "code3": "TJK", "name": "Tajikistan", "number": "+992"},
    {"code": "TZ", "code3": "TZA", "name": "Tanzania, United Republic of", "number": "+255"},
    {"code": "TH", "code3": "THA", "name": "Thailand", "number": "+66"},
    {"code": "TL", "code3": "TLS", "name": "Timor-Leste", "number": "+670"},
    {"code": "TG", "code3": "TGO", "name": "Togo", "number": "+228"},
    {"code": "TK", "code3": "TKL", "name": "Tokelau", "number": "+690"},
    {"code": "TO", "code3": "TON", "name": "Tonga", "number": "+676"},
    {"code": "TT", "code3": "TTO", "name": "Trinidad and Tobago", "number": "+1-868"},
    {"code": "TN", "code3": "TUN", "name": "Tunisia", "number": "+216"},
    {"code": "TR", "code3": "TUR", "name": "Turkey", "number": "+90"},
    {"code": "TM", "code3": "TKM", "name": "Turkmenistan", "number": "+993"},
    {"code": "TC", "code3": "TCA", "name": "Turks and Caicos Islands", "number": "+1-649"},
    {"code": "TV", "code3": "TUV", "name": "Tuvalu", "number": "+688"},
    {"code": "UG", "code3": "UGA", "name": "Uganda", "number": "+256"},
    {"code": "UA", "code3": "UKR", "name": "Ukraine", "number": "+380"},
    {"code": "AE", "code3": "ARE", "name": "United Arab Emirates", "number": "+971"},
    {"code": "GB", "code3": "GBR", "name": "United Kingdom", "number": "+44"},
    {"code": "US", "code3": "USA", "name": "United States", "number": "+1"},
    {"code": "UM", "code3": "UMI", "name": "United States Minor Outlying Islands", "number": ""},
    {"code": "UY", "code3": "URY", "name": "Uruguay", "number": "+598"},
    {"code": "UZ", "code3": "UZB", "name": "Uzbekistan", "number": "+998"},
    {"code": "VU", "code3": "VUT", "name": "Vanuatu", "number": "+678"},
    {"code": "VE", "code3": "VEN", "name": "Venezuela", "number": "+58"},
    {"code": "VN", "code3": "VNM", "name": "Viet Nam", "number": "+84"},
    {"code": "VG", "code3": "VGB", "name": "Virgin Islands, British", "number": "+1-284"},
    {"code": "VI", "code3": "VIR", "name": "Virgin Islands, U.S.", "number": "+1-340"},
    {"code": "WF", "code3": "WLF", "name": "Wallis and Futuna", "number": "+681"},
    {"code": "EH", "code3": "ESH", "name": "Western Sahara", "number": "+212"},
    {"code": "YE", "code3": "YEM", "name": "Yemen", "number": "+967"},
    {"code": "ZM", "code3": "ZMB", "name": "Zambia", "number": "+260"},
    {"code": "ZW", "code3": "ZWE", "name": "Zimbabwe", "number": "+263"}
]
